# 创建/修改该文件的LLM大模型：Arena.ai Agent Mode - Execution Lead Engineer
# 创建时间（北京时间）：2026-07-01 00:00:00

from __future__ import annotations

from _infra.feos.errors import FEOSPolicyError
from _infra.feos.models import EscalationPackage, ExternalResponse, ExternalSession, GatewayCapabilities, HumanAction
from _infra.feos.storage import FEOSWorkspace, sha256_text, write_json


class ClipboardGateway:
    gateway_id = "clipboard"

    def __init__(self, workspace: FEOSWorkspace | None = None, clipboard_adapter=None):
        self.workspace = workspace
        self.clipboard_adapter = clipboard_adapter
        self.capabilities = GatewayCapabilities(gateway="clipboard", supports_clipboard=True, requires_human_review=True, enabled=True)

    def prepare(self, package: EscalationPackage, rendered_markdown: str, policy_result) -> dict:
        if not getattr(policy_result, "allowed", False):
            raise FEOSPolicyError("policy blocked clipboard export")
        if self.workspace is None:
            return {"clipboard_md": rendered_markdown, "content_hash": sha256_text(rendered_markdown)}
        export_dir = self.workspace.case_dir(package.case_id) / "exports"
        export_dir.mkdir(parents=True, exist_ok=True)
        clipboard_path = export_dir / "clipboard.md"
        clipboard_path.write_text(getattr(policy_result, "redacted_text", rendered_markdown) or rendered_markdown, encoding="utf-8")
        content_hash = sha256_text(clipboard_path.read_text(encoding="utf-8"))
        write_json(export_dir / "package.json", package.to_dict())
        write_json(export_dir / "manifest.json", {"package_id": package.id, "case_id": package.case_id, "content_hash": content_hash})
        write_json(export_dir / "redaction_report.json", getattr(policy_result, "redaction_report", {}) or {})
        (export_dir / "evidence_index.md").write_text("# Evidence Index\n\nGenerated by FEOS.\n", encoding="utf-8")
        write_json(export_dir / "audit.json", {"operation": "clipboard_export", "content_hash": content_hash, "human_review_required": True})
        return {"clipboard_md": str(clipboard_path), "content_hash": content_hash}


    def dispatch_copy(self, case_id: str) -> ExternalSession:
        if self.workspace is None:
            raise RuntimeError("workspace required for clipboard dispatch")
        export_dir = self.workspace.case_dir(case_id) / "exports"
        clipboard_path = export_dir / "clipboard.md"
        text = clipboard_path.read_text(encoding="utf-8")
        if self.clipboard_adapter:
            self.clipboard_adapter.copy_text(text)
        session = ExternalSession(
            id=f"session_{case_id}_clipboard",
            case_id=case_id,
            package_id="pkg_unknown",
            human_actions=[HumanAction(type="copied_to_clipboard")],
        )
        session_path = self.workspace.case_dir(case_id) / "sessions" / f"{session.id}.yaml"
        session_path.parent.mkdir(parents=True, exist_ok=True)
        session_path.write_text(session.to_yaml_text(), encoding="utf-8")
        return session

    def receive_response(self, case_id: str, response_text: str | None = None) -> ExternalResponse:
        if self.workspace is None:
            raise RuntimeError("workspace required for clipboard receive")
        text = response_text if response_text is not None else (self.clipboard_adapter.paste_text() if self.clipboard_adapter else "")
        response_id = f"resp_{case_id}_clipboard"
        raw_dir = self.workspace.case_dir(case_id) / "responses"
        raw_dir.mkdir(parents=True, exist_ok=True)
        raw_path = raw_dir / f"{response_id}_raw.md"
        raw_path.write_text(text, encoding="utf-8")
        response = ExternalResponse(id=response_id, case_id=case_id, session_id=f"session_{case_id}_clipboard", raw_ref=str(raw_path.relative_to(self.workspace.root)), content_hash=sha256_text(text), provider="clipboard")
        (raw_dir / f"{response_id}.yaml").write_text(response.to_yaml_text(), encoding="utf-8")
        return response
