"""initial schema

Revision ID: 9dc5086c5ca6
Revises:
Create Date: 2026-08-10 10:50:59.923785

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9dc5086c5ca6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource", sa.String(length=255), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rule_version", sa.String(length=64), nullable=True),
        sa.Column("llm_call_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_log_actor_action", "audit_log", ["actor", "action"], unique=False)
    op.create_index("ix_audit_log_resource", "audit_log", ["resource"], unique=False)
    op.create_index("ix_audit_log_ts", "audit_log", ["ts"], unique=False)
    op.create_table(
        "evidence_policy",
        sa.Column("policy_type", sa.String(length=64), nullable=False),
        sa.Column("region", sa.String(length=8), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.DateTime(), nullable=False),
        sa.Column("effective_to", sa.DateTime(), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("rule_text", sa.String(), nullable=False),
        sa.Column("display_text", sa.String(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "policy_type", "region", "version", name="uq_evidence_policy_type_region_version"
        ),
    )
    op.create_index(
        "ix_evidence_policy_type_region", "evidence_policy", ["policy_type", "region"], unique=False
    )
    op.create_table(
        "family",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_family_name",
        "family",
        ["name"],
        unique=False,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_table(
        "sync_state",
        sa.Column("client_id", sa.String(length=128), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("pending_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_table(
        "baby",
        sa.Column("family_id", sa.String(length=26), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("gestational_age_weeks", sa.Integer(), nullable=True),
        sa.Column("is_preterm", sa.Boolean(), nullable=False),
        sa.Column("birth_weight_g", sa.Integer(), nullable=True),
        sa.Column("current_weight_g", sa.Integer(), nullable=True),
        sa.Column("current_weight_at", sa.DateTime(), nullable=True),
        sa.Column("sex", sa.String(length=8), nullable=True),
        sa.Column("vaccine_region", sa.String(length=8), nullable=False),
        sa.Column("allergies", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.CheckConstraint("sex IN ('male', 'female')", name="ck_baby_sex"),
        sa.ForeignKeyConstraint(["family_id"], ["family.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_baby_family_id", "baby", ["family_id"], unique=False)
    op.create_table(
        "camera_event",
        sa.Column("baby_id", sa.String(length=26), nullable=True),
        sa.Column("family_id", sa.String(length=26), nullable=False),
        sa.Column("device_id", sa.String(length=26), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("clip_path", sa.String(length=512), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["family_id"], ["family.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_camera_event_device_id", "camera_event", ["device_id"], unique=False)
    op.create_index(
        "ix_camera_event_family_occurred",
        "camera_event",
        ["family_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "device",
        sa.Column("family_id", sa.String(length=26), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("fcm_token", sa.String(length=255), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.CheckConstraint("kind IN ('phone', 'camera', 'mmwave', 'mac')", name="ck_device_kind"),
        sa.ForeignKeyConstraint(["family_id"], ["family.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_device_family_id", "device", ["family_id"], unique=False)
    op.create_table(
        "family_knowledge",
        sa.Column("family_id", sa.String(length=26), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["family_id"], ["family.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_id", "key", name="uq_family_knowledge_family_key"),
    )
    op.create_index(
        "ix_family_knowledge_family_id", "family_knowledge", ["family_id"], unique=False
    )
    op.create_table(
        "sensor_event",
        sa.Column("baby_id", sa.String(length=26), nullable=True),
        sa.Column("family_id", sa.String(length=26), nullable=False),
        sa.Column("device_id", sa.String(length=26), nullable=True),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["family_id"], ["family.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sensor_event_device_id", "sensor_event", ["device_id"], unique=False)
    op.create_index(
        "ix_sensor_event_family_received",
        "sensor_event",
        ["family_id", "received_at"],
        unique=False,
    )
    op.create_table(
        "user",
        sa.Column("family_id", sa.String(length=26), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("auth_hash", sa.String(length=255), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["family_id"], ["family.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_user_family_id", "user", ["family_id"], unique=False)
    op.create_table(
        "alert",
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("family_id", sa.String(length=26), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("ack_by", sa.String(length=26), nullable=True),
        sa.Column("ack_at", sa.DateTime(), nullable=True),
        sa.Column("feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "level IN ('gray', 'blue', 'yellow', 'orange', 'red')", name="ck_alert_level"
        ),
        sa.CheckConstraint("status IN ('active', 'acked', 'resolved')", name="ck_alert_status"),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["family_id"], ["family.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_alert_baby_status", "alert", ["baby_id", "status"], unique=False)
    op.create_index("ix_alert_family_level", "alert", ["family_id", "level"], unique=False)
    op.create_table(
        "derived_baby_state",
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("baby_id"),
    )
    op.create_table(
        "observation_event",
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("family_id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=True),
        sa.Column("device_id", sa.String(length=26), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("client_created_at", sa.DateTime(), nullable=False),
        sa.Column("server_received_at", sa.DateTime(), nullable=False),
        sa.Column("raw_input", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("normalized_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("correction_of", sa.String(length=26), nullable=True),
        sa.Column("sync_status", sa.String(length=16), nullable=False),
        sa.Column("processing_status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "processing_status IN ('pending', 'normalized', 'projected')",
            name="ck_observation_event_processing_status",
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'voice_text', 'camera', 'sensor', 'ai', 'system')",
            name="ck_observation_event_source",
        ),
        sa.CheckConstraint(
            "sync_status IN ('pending', 'synced')", name="ck_observation_event_sync_status"
        ),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["family_id"], ["family.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_observation_event_baby_type_start",
        "observation_event",
        ["baby_id", "event_type", sa.literal_column("start_time DESC")],
        unique=False,
    )
    op.create_index(
        "ix_observation_event_correction_of", "observation_event", ["correction_of"], unique=False
    )
    op.create_index(
        "ix_observation_event_family_id", "observation_event", ["family_id"], unique=False
    )
    op.create_table(
        "sleep_session",
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("roi_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.CheckConstraint("state IN ('active', 'paused', 'ended')", name="ck_sleep_session_state"),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sleep_session_baby_started", "sleep_session", ["baby_id", "started_at"], unique=False
    )
    op.create_table(
        "alert_delivery",
        sa.Column("alert_id", sa.String(length=26), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("receipt", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'sent', 'delivered', 'failed')", name="ck_alert_delivery_status"
        ),
        sa.ForeignKeyConstraint(["alert_id"], ["alert.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_alert_delivery_alert_id", "alert_delivery", ["alert_id"], unique=False)
    op.create_table(
        "diaper_log",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["observation_event.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_diaper_log_baby_id", "diaper_log", ["baby_id"], unique=False)
    op.create_table(
        "feeding_log",
        sa.Column("amount_ml", sa.Integer(), nullable=True),
        sa.Column("feeding_type", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["observation_event.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_feeding_log_baby_started", "feeding_log", ["baby_id", "started_at"], unique=False
    )
    op.create_table(
        "growth_log",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["observation_event.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_growth_log_baby_id", "growth_log", ["baby_id"], unique=False)
    op.create_table(
        "jaundice_photo",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["observation_event.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_jaundice_photo_baby_id", "jaundice_photo", ["baby_id"], unique=False)
    op.create_table(
        "media_asset",
        sa.Column("asset_path", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["observation_event.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_media_asset_baby_id", "media_asset", ["baby_id"], unique=False)
    op.create_index("ix_media_asset_event_id", "media_asset", ["event_id"], unique=False)
    op.create_table(
        "medication_log",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["observation_event.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_medication_log_baby_id", "medication_log", ["baby_id"], unique=False)
    op.create_table(
        "milestone_log",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["observation_event.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_milestone_log_baby_id", "milestone_log", ["baby_id"], unique=False)
    op.create_table(
        "sleep_log",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["observation_event.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sleep_log_baby_id", "sleep_log", ["baby_id"], unique=False)
    op.create_table(
        "solid_food_log",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["observation_event.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_solid_food_log_baby_id", "solid_food_log", ["baby_id"], unique=False)
    op.create_table(
        "supplement_log",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["observation_event.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_supplement_log_baby_id", "supplement_log", ["baby_id"], unique=False)
    op.create_table(
        "symptom_event",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["observation_event.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_symptom_event_baby_id", "symptom_event", ["baby_id"], unique=False)
    op.create_table(
        "temperature_log",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["observation_event.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_temperature_log_baby_id", "temperature_log", ["baby_id"], unique=False)
    op.create_table(
        "vaccine_record",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("event_id", sa.String(length=26), nullable=False),
        sa.Column("baby_id", sa.String(length=26), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["baby_id"], ["baby.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["event_id"], ["observation_event.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_vaccine_record_baby_id", "vaccine_record", ["baby_id"], unique=False)

    # ---- 手动补充：updated_at trigger（全表，§6.2）----
    # 每张含 updated_at 列的表，PG trigger 在 UPDATE 时自动刷新 updated_at = now()。
    # 用一个通用函数 + 每表 trigger，避免重复代码。
    op.execute("""
    CREATE OR REPLACE FUNCTION parenting_set_updated_at()
    RETURNS TRIGGER AS $$
    BEGIN
        NEW.updated_at = now() AT TIME ZONE 'UTC';
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    # 对每张含 updated_at 的表挂 trigger（audit_log/sync_state/derived_baby_state 无 updated_at 不挂）。
    for _tbl in (
        "family",
        "user",
        "device",
        "baby",
        "observation_event",
        "feeding_log",
        "diaper_log",
        "sleep_log",
        "temperature_log",
        "supplement_log",
        "vaccine_record",
        "medication_log",
        "symptom_event",
        "jaundice_photo",
        "milestone_log",
        "growth_log",
        "solid_food_log",
        "media_asset",
        "derived_baby_state",
        "alert",
        "alert_delivery",
        "sleep_session",
        "sensor_event",
        "camera_event",
        "family_knowledge",
        "evidence_policy",
    ):
        # 表名加双引号，规避 PG 保留字（如 user）。
        op.execute(
            f'CREATE TRIGGER trg_{_tbl}_updated_at BEFORE UPDATE ON "{_tbl}" '
            f"FOR EACH ROW EXECUTE FUNCTION parenting_set_updated_at();"
        )

    # ---- 手动补充：audit_log append-only（§22.2，REVOKE UPDATE/DELETE）----
    # 角色 parenting 默认无 audit_log 的 UPDATE/DELETE 权限，强制 append-only。
    op.execute("REVOKE UPDATE, DELETE ON TABLE audit_log FROM PUBLIC;")
    op.execute("REVOKE UPDATE, DELETE ON TABLE audit_log FROM parenting;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ---- 手动补充：撤销 updated_at trigger 与函数 ----
    for _tbl in (
        "family",
        "user",
        "device",
        "baby",
        "observation_event",
        "feeding_log",
        "diaper_log",
        "sleep_log",
        "temperature_log",
        "supplement_log",
        "vaccine_record",
        "medication_log",
        "symptom_event",
        "jaundice_photo",
        "milestone_log",
        "growth_log",
        "solid_food_log",
        "media_asset",
        "derived_baby_state",
        "alert",
        "alert_delivery",
        "sleep_session",
        "sensor_event",
        "camera_event",
        "family_knowledge",
        "evidence_policy",
    ):
        op.execute(f'DROP TRIGGER IF EXISTS trg_{_tbl}_updated_at ON "{_tbl}";')
    op.execute("DROP FUNCTION IF EXISTS parenting_set_updated_at();")
    op.drop_index("ix_vaccine_record_baby_id", table_name="vaccine_record")
    op.drop_table("vaccine_record")
    op.drop_index("ix_temperature_log_baby_id", table_name="temperature_log")
    op.drop_table("temperature_log")
    op.drop_index("ix_symptom_event_baby_id", table_name="symptom_event")
    op.drop_table("symptom_event")
    op.drop_index("ix_supplement_log_baby_id", table_name="supplement_log")
    op.drop_table("supplement_log")
    op.drop_index("ix_solid_food_log_baby_id", table_name="solid_food_log")
    op.drop_table("solid_food_log")
    op.drop_index("ix_sleep_log_baby_id", table_name="sleep_log")
    op.drop_table("sleep_log")
    op.drop_index("ix_milestone_log_baby_id", table_name="milestone_log")
    op.drop_table("milestone_log")
    op.drop_index("ix_medication_log_baby_id", table_name="medication_log")
    op.drop_table("medication_log")
    op.drop_index("ix_media_asset_event_id", table_name="media_asset")
    op.drop_index("ix_media_asset_baby_id", table_name="media_asset")
    op.drop_table("media_asset")
    op.drop_index("ix_jaundice_photo_baby_id", table_name="jaundice_photo")
    op.drop_table("jaundice_photo")
    op.drop_index("ix_growth_log_baby_id", table_name="growth_log")
    op.drop_table("growth_log")
    op.drop_index("ix_feeding_log_baby_started", table_name="feeding_log")
    op.drop_table("feeding_log")
    op.drop_index("ix_diaper_log_baby_id", table_name="diaper_log")
    op.drop_table("diaper_log")
    op.drop_index("ix_alert_delivery_alert_id", table_name="alert_delivery")
    op.drop_table("alert_delivery")
    op.drop_index("ix_sleep_session_baby_started", table_name="sleep_session")
    op.drop_table("sleep_session")
    op.drop_index("ix_observation_event_family_id", table_name="observation_event")
    op.drop_index("ix_observation_event_correction_of", table_name="observation_event")
    op.drop_index("ix_observation_event_baby_type_start", table_name="observation_event")
    op.drop_table("observation_event")
    op.drop_table("derived_baby_state")
    op.drop_index("ix_alert_family_level", table_name="alert")
    op.drop_index("ix_alert_baby_status", table_name="alert")
    op.drop_table("alert")
    op.drop_index("ix_user_family_id", table_name="user")
    op.drop_table("user")
    op.drop_index("ix_sensor_event_family_received", table_name="sensor_event")
    op.drop_index("ix_sensor_event_device_id", table_name="sensor_event")
    op.drop_table("sensor_event")
    op.drop_index("ix_family_knowledge_family_id", table_name="family_knowledge")
    op.drop_table("family_knowledge")
    op.drop_index("ix_device_family_id", table_name="device")
    op.drop_table("device")
    op.drop_index("ix_camera_event_family_occurred", table_name="camera_event")
    op.drop_index("ix_camera_event_device_id", table_name="camera_event")
    op.drop_table("camera_event")
    op.drop_index("ix_baby_family_id", table_name="baby")
    op.drop_table("baby")
    op.drop_table("sync_state")
    op.drop_index(
        "ix_family_name", table_name="family", postgresql_where=sa.text("is_deleted = false")
    )
    op.drop_table("family")
    op.drop_index("ix_evidence_policy_type_region", table_name="evidence_policy")
    op.drop_table("evidence_policy")
    op.drop_index("ix_audit_log_ts", table_name="audit_log")
    op.drop_index("ix_audit_log_resource", table_name="audit_log")
    op.drop_index("ix_audit_log_actor_action", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
